name: Bug Report
description: Report a bug to help us fix and improve the project.
labels: ["🐞 BugFix"]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: ⚠️ Current Behavior
      description: Describe the bug you've encountered, including any error messages or unexpected behavior.
      placeholder: Describe the current situation.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected result.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: ✍️ Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        1. In this environment...
        2. With these settings...
        3. Run the '...' command...
        4. An error occurs...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 💾 Relevant Logs
      description: Copy and paste any relevant log output. It will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: |
        Add any related links or relevant information.
    validations:
      required: false

  - type: checkboxes
    id: issue-confirmation
    attributes:
      label: ✅ Checklist
      options:
        - label: I have added the appropriate labels to this issue.
          required: true
